import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import CreatePost from '../components/Modal'

import { Flex, Button } from '@chakra-ui/react'
import AllPost from '../components/AllPost'


const createData = async () => {
  const response = await fetch('/api/create', {
    method: 'POST',
  })

  if (response.ok) {
    window?.location.reload()
  }
}

const deleteData = async (id) => {
  const { status } = await fetch('/api/delete', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ id }),
  })

  if (status === 200) {
    window?.location.reload()
  }
}

export default function Home({posts}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Blog with Xata & Cloudinary</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Blog with Xata & Cloudinary
        </h1>
        <Flex gap={3}>
          <CreatePost />

          <Button className={styles.description} colorScheme='black' variant='outline'  onClick={() => {
                createData()
              }}>
            Check source code
          </Button>
        </Flex>

        <AllPost/>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}